# vim: set filetype=ruby
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "colima"
brew "docker"
brew "neovim"
brew "python"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-symbols-only-nerd-font"
cask "google-chrome"
cask "kitty"
cask "vlc"
