#!/bin/bash
set -euo pipefail

source ./packages.sh

main() {
    #sudo softwareupdate -i -a

    if ! xcode-select -p >/dev/null; then
        echo "Install Xcode command line tools and run script again"
        echo "xcode-select --install"
        exit 1
    fi

    if ! command -v brew >/dev/null; then
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi

    arch -arm64 brew update
    arch -arm64 brew upgrade
    arch -arm64 brew bundle

    mkdir -p ~/projects
    mkdir -p ~/bin

    configure_macos

    ln -sf "$(command -v nvim)" "$HOME/bin/vi"
    ln -sf "$(command -v nvim)" "$HOME/bin/vim"

    install_go_packages

    install_python_packages

    setup_node
    install_node_packages
}

install_go_packages() {
    # shellcheck disable=SC2154
    for go_package in "${go_packages[@]}"; do
        go install "$go_package"
    done
}

install_python_packages() {
    # shellcheck disable=SC2154
    pip3 install --user --upgrade "${pip_packages[@]}"
}

install_node_packages() {
    # shellcheck disable=SC2154
    npm install -g "${npm_packages[@]}"
}

setup_node() {
    fnm install --lts
    fnm use lts-latest
    eval "$(fnm env --shell bash)"
    npm install -g npm@latest
    #npm completion | sudo tee /etc/bash_completion.d/npm >/dev/null
}

configure_macos() {
    defaults write NSGlobalDomain KeyRepeat -int 1
    defaults write NSGlobalDomain InitialKeyRepeat -int 12
    defaults write com.apple.dock autohide -bool true
    defaults write com.Apple.Dock show-recents -bool false
    defaults write com.apple.screensaver askForPassword -int 1
    defaults write com.apple.screensaver askForPasswordDelay -int 0
    defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
    defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
    defaults write .GlobalPreferences com.apple.mouse.scaling -1
}

main "$@"
