#!/bin/bash
set -euo pipefail

mkdir -p ~/screenshots
mkdir -p ~/projects
mkdir -p ~/mnt

sudo timedatectl set-ntp true

sudo pacman -Syu --needed \
    curl \
    jq \
    git \
    vim \
    bc \
    go \
    hub \
    keepassxc \
    htop \
    shellcheck \
    traceroute \
    nmap \
    whois \
    dnsutils \
    tree \
    tmux \
    ufw \
    openssh \
    iperf3 \
    neovim \
    terraform \
    vagrant \
    packer \
    alacritty \
    docker \
    virtualbox \
    virtualbox-host-modules-arch \
    fzf \
    rclone \
    shfmt \
    python \
    python-pip \
    python-pipenv \
    python2 \
    xorg-server-xwayland \
    sway \
    swayidle \
    swaylock \
    grim \
    slurp \
    wl-clipboard \
    ttf-inconsolata \
    ttf-dejavu \
    ttf-liberation \
    ttf-roboto \
    dmenu \
    pavucontrol \
    grc \
    light \
    pulseaudio \
    pulseaudio-alsa \
    pulseaudio-bluetooth \
    bluez-utils \
    bash-completion \
    unzip \
    waybar \
    noto-fonts-emoji \
    pacman-contrib \
    helm \
    reflector \
    transmission-qt \
    fuse2

sudo usermod -aG docker "$USER"

install_pikaur() {
    if command -v pikaur >/dev/null; then
        return 0
    fi
    d="/tmp/pikaur"
    rm -rf "$d"
    git clone https://aur.archlinux.org/pikaur.git "$d"
    (
        cd "$d"
        makepkg -fsri --noconfirm
    )
    rm -rf "$d"
}
install_pikaur

pikaur -S \
    pikaur \
    google-chrome \
    google-cloud-sdk \
    kubectl-bin \
    minikube-bin \
    cfssl \
    ttf-font-awesome-4 \
    kind-bin \
    yq2-bin \
    github-cli \
    aws-cli-v2-bin \
    aws-session-manager-plugin \
    spotify-dev

pip3 install --user --upgrade \
    neovim \
    pynvim \
    black \
    yamllint

sudo usermod -aG video "$USER"

# Add udev rule for light command
sudo tee /usr/lib/udev/rules.d/90-backlight.rules >/dev/null <<EOF
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
ACTION=="add", SUBSYSTEM=="leds", RUN+="/bin/chgrp video /sys/class/leds/%k/brightness"
ACTION=="add", SUBSYSTEM=="leds", RUN+="/bin/chmod g+w /sys/class/leds/%k/brightness"
EOF

install_session_manager_plugin() {
    if command -v session-manager-plugin >/dev/null; then
        return 0
    fi
    d="/tmp/ssm"
    mkdir -p "$d"
    (
        cd "$d" || exit 1
        curl -s -L -O "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb"
        ar x session-manager-plugin.deb data.tar.gz
        tar -xf data.tar.gz
        sudo cp usr/local/sessionmanagerplugin/bin/session-manager-plugin /usr/local/bin/
    )
    rm -rf "$d"
}

install_hyper() {
    if command -v hyper >/dev/null; then
        return 0
    fi
    curl -Lo "$HOME/bin/hyper" https://releases.hyper.is/download/AppImage
    chmod +x "$HOME/bin/hyper"
}
install_hyper
