#!/bin/bash

if [ `whoami` != root ]; then
    echo "Please run this script using sudo"
    exit
fi

function run_as_user {
    sudo -u $SUDO_USER $@
}

update=true
install=true
python=true
ruby=true
rails=true
nodejs=true
haskell=true
yesod=true
networking=true
dotfiles=true

# Settings
hostname=precise3

##############
if [ $update ] ; then
    apt-get update -y
fi

if [ $install ] ; then
    apt-get install -y curl git vim screen openssh-server build-essential
fi

# Python
if [ $python ] ; then
    apt-get install -y python-virtualenv python-dev
    # pychecker, pep8, pylint, pyflakes
fi

# Ruby
# Rails

# Nodejs

# Haskell
if [ $haskell ] || [ $yesod ] ; then
    apt-get install -y haskell-platform hlint
    # Yesod
    if [ $yesod ] ; then
        #run_as_user cabal update
        ##add $HOME/.cabal/bin to path PATH
        #run_as_user echo "export PATH=$PATH:$HOME/.cabal/bin" >> $HOME/.bashrc
        #run_as_user export PATH=$PATH:$HOME/.cabal/bin
        #run_as_user cabal install yesod yesod-bin cabal-dev
        echo "Do something"
    fi
fi

# Networking
if [ $networking ] ; then
    apt-get install -y avahi-daemon
fi

# Hostname
if [ $hostname ] ; then
    echo $hostname > /etc/hostname
    sed -i "s/ubuntu/$hostname/g" /etc/hosts
    hostname $hostname
fi

# Dotfiles
if [ $dotfiles ] ; then
    # TODO not run git clone as root
    run_as_user git clone https://github.com/Mattias-/dotfilez.git
    bash ./dotfilez/install.sh
fi
