#!/bin/bash

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade

brew install wget
brew install git
brew install bash-completion
brew install nmap
brew install awscli
brew install aspell
brew install shellcheck
brew install pssh
brew install jq
brew install fpp
brew install fzf
brew install the_silver_searcher
brew install httpie

brew tap homebrew/dupes
brew install vim --override-system-vi
brew install screen
brew install tcpdump

brew tap homebrew/completions
brew install vagrant-completion

brew tap neovim/neovim
brew install --HEAD neovim
ln -s -f nvim "$(brew --prefix)/bin/vi"
ln -s -f nvim "$(brew --prefix)/bin/vim"

# Install apps with cask
brew tap caskroom/cask
brew cask install google-chrome
brew cask install virtualbox
brew cask install vagrant
brew cask install vagrant-manager
brew cask install gpgtools
brew install keybase # install after gpg
brew cask install keepingyouawake
brew cask install spectacle
brew cask install flux
brew cask install vlc
brew cask install tunnelblick

#brew cask install spotify
#brew cask install skype
#brew cask install dropbox
#brew cask install google-drive
#brew cask install garmin-express

brew tap caskroom/versions
brew cask install iterm2-nightly

brew tap caskroom/fonts
brew cask install font-inconsolata
brew cask install font-inconsolata-g-for-powerline

# Done, time to clean up
brew cask cleanup
brew cleanup

ln -s "$HOME/Library/Mobile Documents/com~apple~CloudDocs/" "$HOME/applecloud"

git clone https://github.com/Mattias-/dotfilez.git
python ./dotfilez/setup_dotfiles.py
