#!/bin/bash

if [ `whoami` = root ]; then
    echo "Please do not run this script as root or using sudo"
    exit
fi

# Settings
# Install python, ruby, haskell, networking

sudo apt-get update -y
sudo apt-get install -y curl git vim screen openssh-server build-essential

# Python
sudo apt-get install -y python-virtualenv python-dev
# pychecker, pep8, pylint, pyflakes

# Ruby
# Rails

# Nodejs

# Haskell
sudo apt-get install -y haskell-platform hlint
# Yesod
#cabal update
##add $HOME/.cabal/bin to path PATH
#echo "export PATH=$PATH:$HOME/.cabal/bin" >> $HOME/.bashrc
#export PATH=$PATH:$HOME/.cabal/bin
#cabal install yesod yesod-bin cabal-dev


# Networking & Hostname
sudo apt-get install -y avahi-daemon
# Set hostname
HOSTNAME=precise2
sudo echo $HOSTNAME > /etc/hostname
sudo sed -i 's/ubuntu/$HOSTNAME/g' /etc/hosts
sudo hostname $HOSTNAME

# Get my dotfiles
# TODO not run git clone as root
git clone https://github.com/Mattias-/dotfilez.git
sudo bash ./dotfilez/install.sh
