#!/bin/bash

if ! xcode-select -p > /dev/null ; then
    xcode-select --install
    echo "Install Xcode command line tools and run script again"
    return
fi

if ! which brew > /dev/null ; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew upgrade

brew install wget
brew install git
brew install bash-completion
brew install nmap
brew install awscli
brew install aspell
brew install shellcheck
brew install pssh
brew install jq
brew install fpp
brew install fzf
brew install the_silver_searcher
brew install httpie
brew install ssh-copy-id
brew install hub
brew install python
brew install python3
brew install tree
brew install ctags
brew install htop
pip install --upgrade pip setuptools ipython flake8 py3kwarn

brew tap homebrew/dupes
brew install vim --override-system-vi
brew install screen
brew install tcpdump

brew tap neovim/neovim
brew install neovim
ln -s -f nvim "$(brew --prefix)/bin/vi"
ln -s -f nvim "$(brew --prefix)/bin/vim"

# Install apps with cask
brew tap caskroom/cask
brew cask install iterm2
brew cask install google-chrome
brew cask install spotify
brew cask install skype
brew cask install vlc
brew cask install flux
brew cask install keepingyouawake
brew cask install spectacle
brew cask install bitbar

#brew cask install dropbox
#brew cask install google-drive
#brew cask install garmin-express
#brew cask install transmission

brew cask install virtualbox
brew cask install vagrant
brew cask install vagrant-manager
brew install vagrant-completion

brew cask install docker
brew install docker-completion
brew install docker-compose-completion

brew cask install gpgtools
brew install keybase # install after gpgtools

brew tap caskroom/fonts
brew cask install font-inconsolata
brew cask install font-inconsolata-g-for-powerline

# Done, time to clean up
brew cask cleanup
brew cleanup

ln -s "$HOME/Library/Mobile Documents/com~apple~CloudDocs/" "$HOME/applecloud"

git clone --recursive https://github.com/Mattias-/dotfilez.git "$HOME/dotfilez" || true
python "$HOME/dotfilez/setup_dotfiles.py"

defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 12
