#!/usr/bin/env bash
files=(.bashrc .bash_profile .gitconfig .screenrc .vim .ssh bin .gitignore_global)
SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )
for file in "${files[@]}"; do
    if [ -e $HOME/$file ]; then
        if [ -L $HOME/$file ]; then
            rm $HOME/$file
        else
            mv $HOME/$file $HOME/$file.bak$(date +%F)
            echo "Renamed old $file to $file.bak$(date +%F)"
        fi
        ln -s  $SCRIPTPATH/$file ~/
    fi
done
