let
  stable = import <stable> {};
  unstable = import <nixpkgs> {};
in [
  unstable.awscli2
  unstable.btop
  unstable.cfssl
  unstable.colima
  unstable.coreutils-prefixed
  unstable.docker-buildx
  unstable.docker-client
  unstable.fd
  unstable.ffmpeg
  unstable.fzf
  unstable.gh
  unstable.gnupg
  unstable.go
  unstable.google-cloud-sdk
  unstable.htop
  unstable.jq
  unstable.neovim
  unstable.nmap
  unstable.nodejs
  unstable.python3
  unstable.pipx
  unstable.ripgrep
  unstable.sad
  unstable.shellcheck
  unstable.shfmt
  unstable.socat
  unstable.ssm-session-manager-plugin
  unstable.starship
  unstable.tcpdump
  unstable.tmux
  unstable.tree
  unstable.tree-sitter
  unstable.yq-go
  unstable.lua-language-server
  unstable.difftastic
  unstable.aws-sam-cli
  unstable.uv
]
