syntax on
set t_Co=256
colorscheme desert256

set number
set ruler
set laststatus=2
set showcmd
set cursorline
set backspace=2
set scrolloff=5

set noswapfile

set splitright
set splitbelow

" Autocomplete filenames
set wildmenu
set wildignore=*.o,*.hi,*.pyc,*.pdf

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Tabs and indents
set tabstop=4
set softtabstop=4 " Make spaces feel like real tabs
set expandtab " When pressing tab, insert [tabstop] spaces
set shiftwidth=4 " When indenting use x spaces
set autoindent " Keep indentation from previous line

" Folding
set foldmethod=indent
set foldlevelstart=20

"Highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red ctermfg=white guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/

set colorcolumn=80

filetype indent on
filetype plugin on

let python_highlight_all=1

let mapleader = "\<Space>"
map <leader>w :set wrap!<cr>
map <leader>p :set paste!<cr>
map <leader><space> za
map <leader>s :setlocal spell! spelllang=en_us<cr>
