version: 2
jobs:
  bash-shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run: find . -type f -name '*.sh' | wc -l
      - run: find . -type f -name '*.sh' | xargs shellcheck --external-sources
  bash-shfmt:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run: go get -u mvdan.cc/sh/cmd/shfmt
      - run: shfmt -f .
      - run: shfmt -i 4 -d $(shfmt -f . | grep -v nvim/pack/my-plugins)

  python-black:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: pip install black
      - run: black . --diff --check
workflows:
  version: 2
  test:
    jobs:
      - bash-shfmt
      - bash-shellcheck
      - python-black
