"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$kubernetes\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[username]
format = "[$user]($style) "
style_user = "yellow"
show_always = true

[hostname]
format = "@ [$hostname]($style) "
style = "blue"
ssh_only = true

[directory]
style = ""
truncation_length = 4

[git_branch]
format = "[$branch]($style) "

[aws]
format = "[$profile]($style) "
disabled = false

[gcloud]
disabled = true
symbol = "☁️ "
format = '[$symbol$project]($style) '

[kubernetes]
disabled = true
format = '[$symbol$context( \($namespace\))]($style) '
[kubernetes.context_aliases]
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[nodejs]
disabled = true
#symbol=""
format="[$symbol($version )]($style)"

[package]
disabled = true

[golang]
disabled = true

[python]
disabled = true

[vagrant]
disabled = true

[terraform]
disabled = true

[ruby]
disabled = true

[docker_context]
disabled = true
