add_newline = false

[username]
format = "[$user]($style) @ "
style_user = "yellow"
show_always = true

[hostname]
format = "[$hostname]($style) "
style = "blue"
ssh_only = false

[directory]
style = ""

[git_branch]
format = "[$branch]($style) "

[aws]
format = ' [$profile]($style) '
disabled = false

[gcloud]
disabled = true
symbol = "☁️ "
format = '[$symbol$project]($style) '

[kubernetes]
disabled = true
format = '[$symbol$context( \($namespace\))]($style) '
[kubernetes.context_aliases]
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[golang]
disabled = true

[python]
disabled = true

[vagrant]
disabled = true

[terraform]
disabled = true

[ruby]
disabled = true
