name: pre-commit

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: go install mvdan.cc/sh/v3/cmd/shfmt
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
