name: pre-commit

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.3'
    - run: |
        go install mvdan.cc/sh/v3/cmd/shfmt@latest
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
